services:
  web:
    build:
      context: .
      target: development
    environment:
      - FLASK_ENV=development
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    stop_signal: SIGINT